// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzihagvdpdjcoyjpvyvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6aWhhZ3ZkcGRqY295anB2eXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzM2NzQsImV4cCI6MjA3NzE0OTY3NH0.2y2vuzaq9dKDrJIyjbAfcNAgrxVEpxeYwS5xNHSrqYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
  accessToken: async () => {
    try {
      const clerk = (window as any).Clerk;
      if (clerk?.session) {
        // Native Clerk <> Supabase third-party integration: use the default session token.
        const token = await clerk.session.getToken();
        if (token) return token;
      }
    } catch (error) {
      console.error("Failed to retrieve Clerk token for Supabase:", error);
    }
    return SUPABASE_PUBLISHABLE_KEY;
  },
});

// Mock/patch Supabase Auth to bridge and resolve to Clerk's active session
const getClerkSession = () => {
  const clerk = (window as any).Clerk;
  if (!clerk?.session || !clerk?.user) return null;
  return {
    access_token: "clerk-bridged-token",
    token_type: "bearer",
    expires_in: 3600,
    refresh_token: "clerk-bridged-refresh",
    user: {
      id: clerk.user.id,
      email: clerk.user.primaryEmailAddress?.emailAddress || "",
      created_at: clerk.user.createdAt ? new Date(clerk.user.createdAt).toISOString() : new Date().toISOString(),
      app_metadata: {},
      user_metadata: {
        first_name: clerk.user.firstName,
        last_name: clerk.user.lastName,
      },
      aud: "authenticated",
      role: "authenticated",
      email_confirmed_at: new Date().toISOString()
    }
  };
};

const customAuth = {
  getSession: async () => {
    const session = getClerkSession();
    return { data: { session }, error: null };
  },
  getUser: async () => {
    const session = getClerkSession();
    return { data: { user: session?.user || null }, error: null };
  },
  onAuthStateChange: (callback: any) => {
    const trigger = () => {
      const session = getClerkSession();
      callback(session ? "SIGNED_IN" : "SIGNED_OUT", session);
    };
    
    const clerk = (window as any).Clerk;
    let unsub = () => {};
    if (clerk) {
      unsub = clerk.addListener(({ session }: any) => {
        const s = getClerkSession();
        callback(session ? "SIGNED_IN" : "SIGNED_OUT", s);
      });
    } else {
      // Graceful fallback if Clerk isn't initialized yet
      setTimeout(trigger, 500);
      setTimeout(trigger, 1500);
    }
    
    return {
      data: {
        subscription: {
          unsubscribe: unsub
        }
      }
    };
  },
  signOut: async () => {
    try {
      const clerk = (window as any).Clerk;
      if (clerk) {
        await clerk.signOut();
      }
    } catch (err) {
      console.error("Clerk sign out error:", err);
    }
    return { error: null };
  }
};

Object.defineProperty(supabase, 'auth', {
  value: customAuth,
  writable: true,
  configurable: true
});